### ISSUE TITLE
support multiple littles cofronting

### ISSUE THREAD

**Issue by herkhinah** [Gankra/cargo-mommy#19]
mew, not sure if it's abdl or plurality related (or both) but wei have multiple littles sometimes blending at the same time. would a pull request for multiple littles be welcome? also our caregiver also needs support sometime.

**Comment by Gankra** [comment]
PRS WELCOME I HAVE NO IDEA WHAT THIS WOULD LOOK LIKE

**Comment by Gankra** [comment]
#43 might actually implement a pretty robust solution for a plural system?

you will now be able to setup several copies of cargo-mommy with `cargo mommy i mean jane`, `cargo mommy i mean sam`, ... and then `cargo jane` and `cargo sam` would both work, and both have independent configurations to read from, so you can rapidly alternative whole configurations.

That plus the usual support for `CARGO_MOMMYS_LITTLE="boy/girl/cat"` (selection being sampled randomly from the 3 choices given), that seems like a *pretty* robust system for however you could want to express your plurality..?

**Comment by Gankra** [comment]
Gonna close this as resolved with https://faultlore.com/cargo-mommy/book/customize/true-roles.html but lmk if insufficient
