### ISSUE TITLE
Forking and continuing, merging PRs etc

### ISSUE THREAD

**Issue by lukas-the-wizard** [Gankra/cargo-mommy#21]
Might fork it for maintaining it, 
i am new to git so i might need some help.
https://github.com/lukas-the-wizard/cargo-mommy-ce

Anyone who wants to help and do this, reply.
I am not interested in doing duplicate work, so if @Gankra continues here, i might stop mine and commit here.

thanks for reading

PS: also my social, so you know who I am: https://tech.lgbt/@lukasfr

**Comment by Gankra** [comment]
I AM BACK (FOR NOW)
