### ISSUE TITLE
buttplug.io  integration 

### ISSUE THREAD

**Issue by Ciubix8513** [Gankra/cargo-mommy#24]
An option to integrate with  [buttplug.io](https://buttplug.io/) it can make coding extra fun and encourage you to fix all your issues~

**Comment by Gankra** [comment]
buttplug.io integration is provided by https://github.com/Shadlock0133/cargo-vibe and the fact that both cargo subcommands forward execution back to cargo with just their own args popped.

`cargo mommy vibe test` should just work

but that should be doc'd

**Comment by Gankra** [comment]
YEP IT SURE DOES

didn't even set anything up and my xbox one controller jump scared me and almost fell of my desk

**Comment by snaeker58** [comment]
> YEP IT SURE DOES
> 
> didn't even set anything up and my xbox one controller jump scared me and almost fell of my desk

“Xbox controller” 🤨

**Comment by elfeiin** [comment]
why

just why

**Comment by LunarEclipse363** [comment]
> why
> 
> just why

Some people just want Mommy to give them extra encouragement~

**Comment by Ciubix8513** [comment]
>why
>
>just why


Science isn't about WHY. It's about WHY NOT. Why is so much of our science dangerous? Why not marry safe science if you love it so much. In fact, why not invent a special safety door that won't hit you on the butt on the way out, because you are fired

**Comment by ShadowJonathan** [comment]
> why
> 
> just why

because we're not corporate drones

(though some of us are other kinds of drones)

**Comment by magicgoose** [comment]
I started to re-run successful builds, am I using it right?

**Comment by Gankra** [comment]
https://faultlore.com/cargo-mommy/book/customize/nsfw.html#buttplugio-support
