### ISSUE TITLE
Would a standalone binary work the same or better than a cargo extension?

### ISSUE THREAD

**Issue by VixieTSQ** [Gankra/cargo-mommy#6]
The more I've been thinking, the more I think that this doesn't actually need to a cargo extension. It doesn't get much from it at all. Although this probably is just a side product of wanting to learn how cargo extensions work, I think it's done it's job for that use case. I can see one problem stemming from converting this to a standalone binary: people may try to use it in contexts outside of the rust compiler, and that means any 'compiling'-specific responses may not make sense, which I think would be quite sad and restrictive.

**Comment by VixieTSQ** [comment]
If you need more something to push you over the edge, the crate name `mommy` is up for grabs.

**Comment by Gankra** [comment]
nah
