### ISSUE TITLE
What the actual fuck

### ISSUE THREAD

**Issue by Collbrothers** [Gankra/cargo-mommy#8]

**Comment by angstyfrostyneko** [comment]
mommy 👍

**Comment by luciusmagn** [comment]
It's the christmas surprise we didn't need, but totally deserved

**Comment by jadelily18** [comment]
> It's the christmas surprise we didn't need, but totally deserved

I'm sorry for whatever the fuck i did to deserve this

**Comment by Gankra** [comment]
GIT GUD
